address
e
RANDOM
Expected an exception to have been thrown
getMessage
conf
nextLong
when
mockFactory
call
fail
doThrow
contains
createSocket
stop
assertTrue
mock
client
Injected fault
testSocketFactoryException
127.0.0.1
