
EXIT_INTERRUPTED
getName
escalator
 call the interrupt operation directly
e
isForcedShutdownTimedOut() == true in 
assertFalse
testInterruptEscalationShutdown
interrupted
isSignalAlreadyReceived() == false in 
assertExceptionDetails
INT
isForcedShutdownTimedOut
setService
fail
Expected an exception to be raised in 
isSignalAlreadyReceived
 now interrupt it a second time and expect it to escalate to a halt
assertStopped
assertTrue
service
 the service is now stopped
launcher
