server
getDefaultSocketFactory
testRTEDuringConnectionSetup
conf
when
doAnswer
assertTrue
StringUtils
client
info
address
e
LOG
RANDOM
Expected an exception to have been thrown
start
 Call should fail due to injected exception.
stringifyException
caught expected exception
 (i.e. it should not have cached a half-constructed connection)
nextLong
spyFactory
getConnectAddress
call
fail
contains
NetUtils
createSocket
answer
stop
Mockito
reset
Injected fault
spy
 throw an RTE when setSoTimeout is called.
